// pages/index.js

import Head from "next/head";

export default function Homepage() {
  return (
    <div className="min-h-screen bg-gray-100">
      <Head>
        <title>CMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="bg-blu shadow">
        <div className="container mx-auto px-4 py-6 flex justify-between items-center">
          <h1 className="text-3xl font-bold text-sky-600">CMS</h1>
          <nav>
            <a href="#home" className="text-gray-600 hover:text-gray-800 mx-2">
              Home
            </a>
            <a href="#about" className="text-gray-600 hover:text-gray-800 mx-2">
              About dss
            </a>
            <a
              href="#contact"
              className="text-gray-600 hover:text-gray-800 mx-2"
            >
              Contact
            </a>
            <a
              href="#contact"
              className="text-gray-600 hover:text-gray-800 mx-2"
            >
              Signup
            </a>
            <a
              href="#contact"
              className="text-gray-600 hover:text-gray-800 mx-2"
            >
              Login
            </a>
          </nav>
        </div>
      </header>

      <main className="container mx-auto px-4 py-10">
        <section id="home" className="text-center">
          <h2 className="text-3xl font-bold mb-4 text-sky-700">
            Welcome to our CSM Paltform
          </h2>
          <p className="text-gray-700 mb-8">
            This is our home page for our CMS.
          </p>
          <button className="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600">
            Get Started
          </button>
        </section>
        <section  id="about" className="mt-16">
        <h2 className="text-2xl font-bold mb-2 text-sky-600 ">About Us</h2>
          <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div class="bg-sky-500 rounded-lg shadow-md p-4 hover:bg-sky-600" >
              <h3 class="font-bold text-xl mb-2 text-black">What you can do ?</h3>
              <p class="text-black">
              Empower yourself to create and manage stunning websites without
              needing to be a coding whiz. Our user-friendly CMS platform
              provides everything you need to get your project off the ground
              and thriving online. Craft engaging content, manage user
              permissions, and keep your website fresh – all from a single,
              intuitive interface.
              </p>
            </div>
            <div class="bg-sky-500 rounded-lg shadow-md p-4 hover:bg-sky-600">
              <h3 class="font-bold text-xl mb-2 text-black">What you will get ?</h3>
              <p class="text-black">
              Whether you're a seasoned professional or a complete beginner, our
              platform caters to all skill levels. Drag-and-drop functionality
              makes creating beautiful pages a breeze, while a vast library of
              customizable templates ensures your website reflects your unique
              brand identity. Dive into the world of content creation with
              confidence and showcase your vision to the world.
              </p>
            </div>
          </div>
        </section>

        
        <section id="contact" className="mt-16">
          <h2 className="text-2xl font-bold mb-4 text-sky-600">Contact Us</h2>
          <form className="bg-white shadow-md rounded px-8 pt-6 pb-50 mb-4">
            <div className="mb-4">
              <label
                className="block text-gray-700 text-sm font-bold mb-2"
                htmlFor="name"
              >
                Name
              </label>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="name"
                type="text"
                placeholder="Your name"
              />
            </div>
            <div className="mb-4">
              <label
                className="block text-gray-700 text-sm font-bold mb-2"
                htmlFor="email"
              >
                Email
              </label>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="email"
                type="email"
                placeholder="Your email"
              />
            </div>
            <div className="mb-6">
              <label
                className="block text-gray-700 text-sm font-bold mb-2"
                htmlFor="message"
              >
                Message
              </label>
              <textarea
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="message"
                placeholder="Your message"
                rows="4"
              ></textarea>
            </div>
            <div className="flex items-center justify-between">
              <button
                className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
                type="button"
              >
                Send
              </button>
            </div>
          </form>
        </section>
      </main>

      <footer class="bg-sky-500 text-white py-4">
        <div class="container mx-auto px-4 flex flex-wrap justify-between">
          <p class="text-xs ">© 2024 - Your Company Name</p>
          <ul class="flex space-x-4">
            <li>
              <a href="#" class="hover:text-sky-100">
                About Us
              </a>
            </li>
            <li>
              <a href="#" class="hover:text-sky-100">
                Contact
              </a>
            </li>
            <li>
              <a href="#" class="hover:text-sky-100">
                Terms & Conditions
              </a>
            </li>
          </ul>
        </div>
      </footer>
    </div>
  );
}
